version: 2

jobs:
  build:
    docker:
      - image: golang:1.24.0
    working_directory: /gopath/src/github.com/vcaesar/gcv
    steps:
      - checkout
      - run: apt update
      - run:
          apt -y install gcc libc6-dev
          libx11-dev xorg-dev libxtst-dev
          xsel xclip
          libopencv-dev
          # libpng++-dev
          # xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev
      - run: apt -y install xvfb
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: xvfb-run go test -v ./...
      # codecov.io
      - run: go test -v -covermode=count -coverprofile=coverage.out
      - run: bash <(curl -s https://codecov.io/bash)
