name: Go
on: [push]
jobs:
  test:
    # name: build
    strategy:
      matrix:
        # go: [1.16.x, 1.17.x]
        os: [macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.24.0
        uses: actions/setup-go@v1
        with:
          go-version: 1.24.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get opencv
        run: |
          brew install opencv

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v .
